### ISSUE TITLE
Argument `expires` is missing.

### ISSUE THREAD

**Issue by NedcloarBR** [mgcrea/fastify-session-prisma-store#2]
```
PrismaClientValidationError:
Invalid `prisma.session.upsert()` invocation:

{
  create: {
    sid: "tJ4iZu7mJF8yt7unqeomX",
    data: {},
    expiresAt: new Date("2024-04-10T14:16:26.146Z"),
+   expires: DateTime
  },
  update: {
    data: {},
    expiresAt: new Date("2024-04-10T14:16:26.146Z")
  },
  where: {
    sid: "tJ4iZu7mJF8yt7unqeomX"
  }
}

Argument `expires` is missing.
    at Tn (/home/nedcloarbr/Projetos/N-D-B/node_modules/@prisma/client/runtime/library.js:115:5888)
    at In.handleRequestError (/home/nedcloarbr/Projetos/N-D-B/node_modules/@prisma/client/runtime/library.js:122:6510)
    at In.handleAndLogRequestError (/home/nedcloarbr/Projetos/N-D-B/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/home/nedcloarbr/Projetos/N-D-B/node_modules/@prisma/client/runtime/library.js:122:5896)
    at l (/home/nedcloarbr/Projetos/N-D-B/node_modules/@prisma/client/runtime/library.js:127:10871)
    at PrismaStore.set (/home/nedcloarbr/Projetos/N-D-B/node_modules/@mgcrea/fastify-session-prisma-store/src/PrismaStore.ts:41:5)
    at _Session.save (/home/nedcloarbr/Projetos/N-D-B/node_modules/@mgcrea/fastify-session/src/session/Session.ts:220:5)
    at Object.<anonymous> (/home/nedcloarbr/Projetos/N-D-B/node_modules/@mgcrea/fastify-session/src/plugin.ts:130:7)
```

**Comment by NedcloarBR** [comment]
Bug fixed
The [Readme](https://github.com/mgcrea/fastify-session-prisma-store/blob/master/README.md#quickstart) shows this Prisma Schema
```prisma
model Session {
  id        BigInt   @id @default(autoincrement()) @db.BigInt
  sid       String   @unique
  expires   DateTime
  data      Json
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  @@map("sessions")
}
```
But the actual [Schema](https://github.com/mgcrea/fastify-session-prisma-store/blob/master/prisma/schema.prisma) is
```prisma
model Session {
  id        BigInt   @id @default(autoincrement()) @db.BigInt
  sid       String   @unique
  data      Json
  expiresAt DateTime
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map("sessions")
}
```
